version: 0.0
Resources:
- TargetService:
Type: AWS::ECS::Service
Properties:
TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/pms-auth-task-definition-imran:1"
LoadBalancerInfo:
ContainerName: "pms-auth-container-imran"
ContainerPort: 8400
PlatformVersion: "LATEST"
